
---
  - name: Configure OpenLDAP to move old database if needed
    debconf: name=slapd question=slapd/move_old_database vtype=boolean value=true

  - name: Configure OpenLDAP when to dump the old database
    debconf: name=slapd question=slapd/dump_database vtype=string value="when needed"

  - name: Configure domain for OpenLDAP
    debconf: name=slapd question=slapd/domain vtype=string value="{{ inventory_hostname }}.datameer.example"

  - name: Configure memory-mapped database as backend for OpenLDAP
    debconf: name=slapd question=slapd/backend vtype=string value=MDB

  - name: Configure password1 for OpenLDAP
    debconf: name=slapd question=slapd/password1 vtype=string value=1234

  - name: Configure password2 for OpenLDAP
    debconf: name=slapd question=slapd/password2 vtype=string value=1234

  - name: Configure organization for OpenLDAP
    debconf: name=slapd question=shared/organization vtype=string value=datameer

  - name: Configure OpenLDAP to not allow LDAPv2
    debconf: name=slapd question=slapd/allow_ldap_v2 vtype=boolean value=false

  - name: Install OpenLDAP
    apt: name=slapd

  - name: Install LDAP utils
    apt: name=ldap-utils
